# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trezentos
description: Teste para Frond-End Junior - Trezentos
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.trezentos.com.br/" # the base hostname & protocol for your site
exclude: ["bower_components","node_modules", "package.json", "bower.json", "gulpfile.js", "projeto.json", "README.md"]

# Build settings
markdown: kramdown
